### ISSUE TITLE
Error:middlwares.miner:Validation Error: Miner AuthPayload

### ISSUE THREAD

**Issue by Shaners42** [Datura-ai/compute-subnet#37]
Hey, 

I have the below error periodically on an executor which has successful miner communication and points to the Datura validator. No other errors showing up on the Miner or Executor logs. 

Prior to the below errors there is plenty of successful "POST /remove_ssh_key HTTP/1.1" 200 OK""

`ERROR:middlewares.miner:Validation Error: 1 validation error for MinerAuthPayload
  Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value=b'', input_type=bytes]
    For further information visit https://errors.pydantic.dev/2.9/v/json_invalid
INFO:     94.102.49.190:57140 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/opt/pypackages/lib/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/opt/pypackages/lib/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/pypackages/lib/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/pypackages/lib/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/pypackages/lib/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/pypackages/lib/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/opt/pypackages/lib/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/opt/pypackages/lib/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/opt/pypackages/lib/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/opt/pypackages/lib/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/opt/pypackages/lib/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/opt/pypackages/lib/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/app/src/middlewares/miner.py", line 39, in dispatch
    |     return JSONResponse(status_code=422, content={"detail": e.errors()})
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/pypackages/lib/starlette/responses.py", line 184, in __init__
    |     super().__init__(content, status_code, headers, media_type, background)
    |   File "/opt/pypackages/lib/starlette/responses.py", line 41, in __init__
    |     self.body = self.render(content)
    |                 ^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/pypackages/lib/starlette/responses.py", line 187, in render
    |     return json.dumps(
    |            ^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    |     **kw).encode(obj)
    |           ^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    |     chunks = self.iterencode(o, _one_shot=True)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    |     return _iterencode(o, 0)
    |            ^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    |     raise TypeError(f'Object of type {o.__class__.__name__} '
    | TypeError: Object of type bytes is not JSON serializable
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pypackages/lib/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypackages/lib/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypackages/lib/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pypackages/lib/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pypackages/lib/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pypackages/lib/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pypackages/lib/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pypackages/lib/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/opt/pypackages/lib/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/app/src/middlewares/miner.py", line 39, in dispatch
    return JSONResponse(status_code=422, content={"detail": e.errors()})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypackages/lib/starlette/responses.py", line 184, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/opt/pypackages/lib/starlette/responses.py", line 41, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypackages/lib/starlette/responses.py", line 187, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by Shaners42** [comment]
Redeployed the dockers including recreated .env and looks better thanks.
